### ISSUE TITLE
Incompat with NeoForge 21.0.10-beta+

### ISSUE THREAD

**Issue by Lolothepro** [dragon-forge/SolarFluxReborn#30]

**Comment by Zeitheron** [comment]
Crash report?!

**Comment by Lolothepro** [comment]
```
Exception caught during firing event: null
	Index: 0
	Listeners:
		0: org.zeith.solarflux.proxy.SFRClientProxy$$Lambda/0x00007d5244e229a0@3c150a64
		1: org.zeith.hammerlib.core.adapter.LanguageAdapter$$Lambda/0x00007d52451860f0@664b447a
java.lang.ExceptionInInitializerError
	at TRANSFORMER/solarflux@21.0.0/org.zeith.solarflux.proxy.SFRClientProxy.reloadLangs(SFRClientProxy.java:22)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/hammerlib@21.0.4/org.zeith.hammerlib.HammerLib.postEvent(HammerLib.java:243)
	at TRANSFORMER/hammerlib@21.0.4/org.zeith.hammerlib.api.LanguageHelper.reloadLang(LanguageHelper.java:25)
	at TRANSFORMER/hammerlib@21.0.4/org.zeith.hammerlib.api.LanguageHelper.reloadLanguage(LanguageHelper.java:18)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.resources.language.ClientLanguage.localvar$zbk000$hammerlib$map(ClientLanguage.java:523)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.resources.language.ClientLanguage.loadFrom(ClientLanguage.java:49)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.resources.language.LanguageManager.onResourceManagerReload(LanguageManager.java:66)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1158)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:810)
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32)
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Registry is already frozen
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.MappedRegistry.validateWrite(MappedRegistry.java:111)
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.MappedRegistry.createIntrusiveHolder(MappedRegistry.java:382)
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.Item.<init>(Item.java:67)
	at TRANSFORMER/solarflux@21.0.0/org.zeith.solarflux.init.ItemsSF$1.<init>(ItemsSF.java:77)
	at TRANSFORMER/solarflux@21.0.0/org.zeith.solarflux.init.ItemsSF.newMaterial(ItemsSF.java:76)
	at TRANSFORMER/solarflux@21.0.0/org.zeith.solarflux.init.ItemsSF.<clinit>(ItemsSF.java:23)
	... 42 more
```

[crash-2024-06-16_20.17.00-client.txt](https://github.com/user-attachments/files/15859396/crash-2024-06-16_20.17.00-client.txt)

**Comment by Zeitheron** [comment]
Can you please send the full game log? it's the latest.log file located in `.minecraft/logs/latest.log`

**Comment by Lolothepro** [comment]
[latest.log](https://github.com/user-attachments/files/15859520/latest.log)

**Comment by Zeitheron** [comment]
The issue seems to be unrelated to SFR, but is located inside HammerLib instead. I have pushed a new version of HL to fix it. Check and see if that helps!

**Comment by Lolothepro** [comment]
[latest.log](https://github.com/user-attachments/files/15859563/latest.log)

same with [HammerLib](https://modrinth.com/mod/PlkSuVtM) 21.0.5

**Comment by Zeitheron** [comment]
This time your issue is securitycraft. See:
```
[16Jun2024 19:00:00.019] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: securitycraft
java.lang.NoSuchMethodError: 'net.minecraft.client.model.HumanoidModel$ArmPose net.minecraft.client.model.HumanoidModel$ArmPose.create(java.lang.String, boolean, net.neoforged.neoforge.client.IArmPoseTransformer)'
	at TRANSFORMER/securitycraft@1.9.10-beta3/net.geforcemods.securitycraft.ClientHandler.<clinit>(ClientHandler.java:201) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$4(AutomaticEventSubscriber.java:60) ~[loader-4.0.6.jar%23141!/:4.0]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:44) ~[loader-4.0.6.jar%23141!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:126) ~[loader-4.0.6.jar%23141!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:152) ~[loader-4.0.6.jar%23141!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:230) ~[loader-4.0.6.jar%23141!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by Zeitheron** [comment]
I pushed out an update that does remove SolarFlux from the stack trace (hopefully), as it's not the culprit of this right now. Try upgrading to HL 21.0.6 and SFR 21.0.1

**Comment by Zeitheron** [comment]
And be sure to report the stack trace provided above to SecurityCraft devs!

**Comment by Lolothepro** [comment]
ok, ty
